apiVersion: v1
kind: Service
metadata:
  name: {{ template "shortname" . }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: {{ template "fullname" . }}
spec:
  ports:
  - port: {{ .Values.Port.Service }}
    targetPort: {{ .Values.Port.Container }}
    {{ if (and (eq .Values.Service.Type "NodePort") (not (empty .Values.Port.Node))) }}
    nodePort: {{ .Values.Port.Node }}
    {{ end }}
    name: http
    protocol: TCP
  selector:
    component: {{ template "fullname" . }}
  type: {{ .Values.Service.Type }}
  {{ if eq .Values.Service.Type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.LoadBalancerSourceRanges }}
  {{ end }}
